sudo: true
dist: trusty

services:
  - docker

before_script:
  - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
  - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register

jobs:
  include:
    - stage: build rpi image
      script:
        # # prepare qemu
        # - docker run --rm --privileged multiarch/qemu-user-static:register --reset

        # build
        - docker build --file Dockerfile-rpi -t $DOCKER_USERNAME/aqara-mqtt .
        - docker images

        # push image
        - >
          if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            VERSION=$(cat .semver)
            ARCH=rpi
            docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
            docker images
            docker tag $DOCKER_USERNAME/aqara-mqtt $DOCKER_USERNAME/aqara-mqttl:$VERSION-$ARCH
            docker images
            # docker push $DOCKER_USERNAME/aqara-mqtt:$VERSION-$ARCH
          fi