sudo: true
services:
  - docker

env:
  global:
    - IMAGE_NAME=$DOCKER_USERNAME/aqara-mqtt

jobs:
  include:
    - stage: build armhf image
      before_script:
        - VERSION=$(cat .semver)
        - ARCH=armhf

      script:
        # prepare qemu
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset

        # build
        - docker build -t $IMAGE_NAME -f Dockerfile-$ARCH .

        # push image
        - >
          if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION-$ARCH
            docker push $IMAGE_NAME:$VERSION-$ARCH
          fi