sudo: true
services:
  - docker

env:
  global:
    - IMAGE_NAME=$DOCKER_USERNAME/aqara-mqtt

jobs:
  include:
    - stage: build rpi image
      script:
        # prepare qemu
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset

        # build
        - docker build -t $IMAGE_NAME -f Dockerfile-rpi  .
        - docker images

        # push image
        - >
          if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            VERSION=$(cat .semver)
            ARCH=rpi

            docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
            docker images
            docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION-$ARCH
            docker images
            # docker push $IMAGE_NAME:$VERSION-$ARCH
          fi